### ISSUE TITLE
API endpoint people with "since" is inconsistent

### ISSUE THREAD

**Issue by balen** [worldcon75/api#45]
While using the people endpoint for syncing member info with Grenadine. Issue is as follows:

1. Use https://members.worldcon.fi/api/kansa/people to get the initial data. This works and is always consistent i.e. member numbers and people ids for the person are invariant.

2. Use https://members.worldcon.fi/api/kansa/people with the since parameter is no consistent. If a person has update information their id and member number is not the same as from the first initial data. Additionally it appears that the member number is from a different member in Kansa. So the the call with the since parameter is mixing up membership numbers and status.

**Comment by eemeli** [comment]
I'm pretty sure this is caused by something other than `since` resulting in inconsistent data. Both queries are handled by [`kansa/lib/people.js`](https://github.com/worldcon75/api/blob/master/kansa/lib/people.js), with the SQL being formed with the parameter on line 32,  and without on line 91. As you may note, both are using the same initial `SELECT`, and one form just appends `WHERE last_modified > $(since)` to it.

I would guess that the apparent inconstancy might be arising from individuals with more than one membership to their name.
